In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
def load_coffee_data():
    """ Creates a coffee roasting data set.
        roasting duration: 12-15 minutes is best
        temperature range: 175-260C is best
    """
    rng = np.random.default_rng(2)
    X = rng.random(400).reshape(-1,2)
    X[:,1] = X[:,1] * 4 + 11.5          # 12-15 min is best
    X[:,0] = X[:,0] * (285-150) + 150  # 350-500 F (175-260 C) is best
    Y = np.zeros(len(X))

    i=0
    for t,d in X:
        y = -3/(260-175)*t + 21
        if (t > 175 and t < 260 and d > 12 and d < 15 and d<=y ):
            Y[i] = 1
        else:
            Y[i] = 0
        i += 1

    return (X, Y.reshape(-1,1))

In [3]:
def dense(x,w,b):
    z = np.matmul(x,w) + b
    return (1/(1+np.exp(-z)))

In [4]:
x,y = load_coffee_data()
print(x.shape)

(200, 2)


In [5]:
W1_tmp = np.array( [[-8.93,  0.29, 12.9 ], [-0.1,  -7.32, 10.81]] )
b1_tmp = np.array( [-9.82, -9.28,  0.96] )
a1 = dense(x,W1_tmp,b1_tmp)

W2_tmp = np.array( [[-31.18], [-27.59], [-32.56]] )
b2_tmp = np.array( [15.41] )
a2 = dense(a1,W2_tmp,b2_tmp)
print(a2)


[[3.56327729e-08]
 [3.56327720e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327663e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.56327729e-08]
 [3.563277

<ipython-input-3-4dd1e45419a5>:3: RuntimeWarning: overflow encountered in exp
  return (1/(1+np.exp(-z)))


In [6]:
for i in range(a2.shape[0]):
    if(a2[i]<0.5):
        a2[i]=0
    else:
        a2[i]=1
print(a2)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.

In [7]:
print(f"Temperature Max, Min pre normalization: {np.max(x[:,0]):0.2f}, {np.min(x[:,0]):0.2f}")
print(f"Duration    Max, Min pre normalization: {np.max(x[:,1]):0.2f}, {np.min(x[:,1]):0.2f}")
norm_l = tf.keras.layers.Normalization(axis=-1)
norm_l.adapt(x)  # learns mean, variance
Xn = norm_l(x)
print(f"Temperature Max, Min post normalization: {np.max(Xn[:,0]):0.2f}, {np.min(Xn[:,0]):0.2f}")
print(f"Duration    Max, Min post normalization: {np.max(Xn[:,1]):0.2f}, {np.min(Xn[:,1]):0.2f}")

Temperature Max, Min pre normalization: 284.99, 151.32
Duration    Max, Min pre normalization: 15.45, 11.51
Temperature Max, Min post normalization: 1.66, -1.69
Duration    Max, Min post normalization: 1.79, -1.70


In [8]:
tf.random.set_seed(1234)
model = Sequential(
    [
        tf.keras.Input(shape=(400,)),
        Dense(3,activation='sigmoid',name='layer1'),
        Dense(1,activation='sigmoid',name='layer2')
    ]
)
model.summary()
W1, b1 = model.get_layer("layer1").get_weights()
W2, b2 = model.get_layer("layer2").get_weights()
print(f"W1{W1.shape}:\n", W1, f"\nb1{b1.shape}:", b1)
print(f"W2{W2.shape}:\n", W2, f"\nb2{b2.shape}:", b2)
model.compile()
model.fit()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (None, 3)                 1203      
                                                                 
 layer2 (Dense)              (None, 1)                 4         
                                                                 
Total params: 1207 (4.71 KB)
Trainable params: 1207 (4.71 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
W1(400, 3):
 [[ 0.11173872  0.05032537  0.08673467]
 [ 0.03132419 -0.08159788 -0.11688118]
 [-0.01683845  0.01314915  0.02152882]
 ...
 [-0.07862772  0.01169904  0.08415084]
 [-0.0526545  -0.10689205 -0.04828272]
 [ 0.06835822 -0.08231766  0.12136028]] 
b1(3,): [0. 0. 0.]
W2(3, 1):
 [[-0.42512244]
 [ 0.16724122]
 [-1.0193732 ]] 
b2(1,): [0.]


ValueError: ignored